import bgbooks from '../image/bgbooks.jpg'

export const styles = {
  pageContainer: {
    backgroundColor: '#1b263b',
    backgroundImage: `url(${bgbooks})`,
    backgroundSize: 'cover',
    backgroundAttachment: 'fixed' as 'fixed',
    minHeight: '100vh',
    paddingBottom: '50px',
  },

  navBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 30px',
    backgroundColor: '#0d284f',
    color: '#ffffff',
    position: 'sticky' as 'sticky',
    top: 0,
    zIndex: 1000,
    boxShadow: '0 2px 5px rgba(0, 0, 0, 0.5)'
  },
  backButton: {
    color: '#ffffff',
    textDecoration: 'none',
    fontSize: '14px',
    padding: '5px 10px',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
  },
  title: {
    fontSize: '28px',
    fontWeight: '300',
    textAlign: 'center' as 'center',
    flexGrow: 1,
    margin: 0
  },
  searchBar: {
    padding: '8px 15px',
    borderRadius: '20px',
    border: 'none',
    outline: 'none',
    width: '200px',
    fontSize: '14px',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    color: '#ffffff',
  },
  userContainer: {
    position: 'relative' as 'relative',
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
  },
  userButton: {
    backgroundColor: 'transparent',
    color: '#ffffff',
    border: '1px solid #ffffff',
    padding: '8px 15px',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '14px'
  },

  content: {
    padding: '20px 80px',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  categoryTitle: {
    color: '#ffffff',
    fontSize: '24px',
    fontWeight: 'bold',
    marginTop: '40px',
    marginBottom: '20px',
    paddingBottom: '5px',
    textShadow: '0 0 5px #000000',
  },
  bookRowStatic: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '30px',
    paddingBottom: '20px',
  },
  bookCard: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-end',
    height: '280px',
    textAlign: 'center' as 'center',
    cursor: 'pointer',
  },
  bookCover: {
    width: 'auto',
    height: 'auto',
    maxWidth: '100%',
    objectFit: 'contain' as 'contain',
    borderRadius: '4px',
    boxShadow: '0 8px 20px rgba(0, 0, 0, 0.7)',
    transition: 'transform 0.2s',
    maxHeight: '280px',
  },
  navButton: {
        position: 'absolute' as 'absolute',
        top: '50%',
        transform: 'translateY(-50%)',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        color: '#ffffff',
        border: 'none',
        width: '40px',
        height: '40px',
        fontSize: '20px',
        cursor: 'pointer',
        zIndex: 10,
        borderRadius: '50%',
        transition: 'background-color 0.3s, opacity 0.3s',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        boxShadow: '0 0 10px rgba(0,0,0,0.5)',
  }
}
